config/routes.rb
Rails.application.routes.draw do
  root 'import_files#index'

  resources :import_files
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import_file.rb
class ImportFile < ApplicationRecord
  attr_accessor :file
  has_many :sales

  def save
    super
    save_sales
  end

  def gross_revenue
    sales.map { |n| n.unit_price * n.amount }.reduce(&:+)
  end

  private
    def save_sales
      data = file.read.split(/\r?\n|\r/).drop(1)
      values = get_sellings_from_data(data)
      fast_insert(values)
    end

    def get_sellings_from_data(data)
      values = []

      data.drop(0).each do |selling|
        s = selling.split(/\t/)
        values << "(#{id}, \"#{s[0]}\", \"#{s[1]}\", #{s[2].to_f}, #{s[3].to_f}, \"#{s[4]}\", \"#{s[5]}\")"
      end

      values
    end

    def fast_insert(values)
      ActiveRecord::Base.connection.execute(
        "INSERT INTO sales (import_file_id, buyer, description, unit_price, amount, address, provider) VALUES #{values.join(',')}"
      )
    end
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :import_file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/import_files_controller.rb
class ImportFilesController < ApplicationController
  before_action :set_imported_file, only: [:show]

  def index
    @imported_files = ImportFile.all
  end

  def new
    @import_file = ImportFile.new
  end

  def create
    @import_file = ImportFile.new
    @import_file.file = sellings_params[:file]
    @import_file.file_name = sellings_params[:file].original_filename
    
    respond_to do |format|
      if @import_file.save
        format.html { redirect_to import_file_path @import_file }
      end
    end
    
  end

  def show
  end

  private
    def sellings_params
      params.require(:import_file).permit(:file)
    end

    def set_imported_file
      @imported_file = ImportFile.find(params[:id])
    end
end

app/controllers/sellings_controller.rb
class SellingsController < ApplicationController

  def index
    @sellings = Selling.all
  end

  def new
    @selling = Selling.new
  end

  def create
    data = sellings_params[:file].read.split(/\r?\n|\r/).drop(1)
    sellings = get_sellings_from_data(data)

    fast_insert(sellings)

    redirect_to sellings_path
  end

  def show
  end

  private
    def sellings_params
      params.require(:selling).permit(:file)
    end

    def get_sellings_from_data(data)
      values = []

      data.drop(0).each do |selling|
        s = selling.split(/\t/)
        values << "(\"#{s[0]}\", \"#{s[1]}\", #{s[2].to_f}, #{s[3].to_f}, \"#{s[4]}\", \"#{s[5]}\")"
      end

      values
    end

    def fast_insert(values)
      ActiveRecord::Base.connection.execute(
        "INSERT INTO sellings (buyer, description, unit_price, amount, address, provider) VALUES #{values.join(',')}"
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/import_files/_form.html.erb
<%= form_for @import_file do |form| %>
  <div style="margin: 1%;">
    <div class="custom-file">
      <%= form.file_field :file, class: "custom-file-input", id: "file" %><br>
      <label class="custom-file-label" for="file">Selecione o arquivo</label>
    </div>
  </div>
  
  <div align="center">
    <%= form.submit "Importar", class: "btn btn-success btn-lg" %>
  </div>
  
<% end %>

app/views/import_files/index.html.erb
<div class=scroll-table>
  <table class="table table-sm">
    <thead>
      <tr>
        <th>Nome do arquivo</th>
        <th>Data de importação</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% @imported_files.each do |file| %>
        <tr>
          <td><%= file.file_name %></td>
          <td><%= file.created_at %></td>
          <td><%= link_to "Visualizar", file, class: "btn btn-outline-primary btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div align="center">
  <%= link_to "Importar arquivo", new_import_file_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/import_files/new.html.erb
<%= render "form" %>

app/views/import_files/show.html.erb
<h3>Receita bruta: <%= number_to_currency @imported_file.gross_revenue %></h3>

<div class="scroll-table">
  <table class="table table-sm">
    <tr>
      <th>Comprador</th>
      <th>Descrição</th> 
      <th>Preço unitário</th>
      <th>Quantidade</th>
      <th>Endereço</th>
      <th>Fornecedor</th>
    </tr>
    <% @imported_file.sales.each do |sale| %>
      <tr>
        <td><%= sale.buyer %></td>
        <td><%= sale.description %></td>
        <td><%= number_to_currency sale.unit_price %></td>
        <td><%= sale.amount %></td>
        <td><%= sale.address %></td>
        <td><%= sale.provider %></td>
      </tr>
    <% end %>
  </table>
</div>



<%= link_to "Voltar", import_files_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NamaFileParser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/sellings/_form.html.erb
<%= form_for @selling do |form| %>
  <%= form.file_field :file %><br>

  <%= form.submit %>
<% end %>

app/views/sellings/index.html.erb
<table style="width:100%">
  <tr>
    <th>Comprador</th>
    <th>Descrição</th> 
    <th>Preço unitário</th>
    <th>Quantidade</th>
    <th>Endereço</th>
    <th>Fornecedor</th>
  </tr>
  <% @sellings.each do |sale| %>
    <tr>
      <td><%= sale.buyer %></td>
      <td><%= sale.description %></td>
      <td><%= sale.unit_price %></td>
      <td><%= sale.amount %></td>
      <td><%= sale.address %></td>
      <td><%= sale.provider %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Importar arquivo", new_selling_path %>